import { Command, Home, MessageSquare, Shield, Users } from "lucide-react";

export const getRoutes = (serverId: string) => [
  {
    href: `/servers/${serverId}`,
    icon: Home,
    title: "Dashboard",
  },
  {
    href: `/servers/${serverId}/members`,
    icon: Users,
    title: "Members",
  },
  {
    href: `/servers/${serverId}/roles`,
    icon: Shield,
    title: "Roles",
  },
  {
    href: `/servers/${serverId}/logs`,
    icon: Command,
    title: "Logs",
  },
  {
    href: `/servers/${serverId}/messaging`,
    icon: MessageSquare,
    title: "Messaging",
  },
];

export const DiscordPermissions = {
  CreateInstantInvite: "Create Instant Invite",
  KickMembers: "Kick Members",
  BanMembers: "Ban Members",
  Administrator: "Administrator",
  ManageChannels: "Manage Channels",
  ManageGuild: "Manage Guild",
  AddReactions: "Add Reactions",
  ViewAuditLog: "View Audit Log",
  PrioritySpeaker: "Priority Speaker",
  Stream: "Stream",
  ViewChannel: "View Channel",
  SendMessages: "Send Messages",
  SendTTSMessages: "Send TTS Messages",
  ManageMessages: "Manage Messages",
  EmbedLinks: "Embed Links",
  AttachFiles: "Attach Files",
  ReadMessageHistory: "Read Message History",
  MentionEveryone: "Mention Everyone",
  UseExternalEmojis: "Use External Emojis",
  ViewGuildInsights: "View Guild Insights",
  Connect: "Connect",
  Speak: "Speak",
  MuteMembers: "Mute Members",
  DeafenMembers: "Deafen Members",
  MoveMembers: "Move Members",
  UseVAD: "Use Voice Activity Detection",
  ChangeNickname: "Change Nickname",
  ManageNicknames: "Manage Nicknames",
  ManageRoles: "Manage Roles",
  ManageWebhooks: "Manage Webhooks",
  ManageEmojisAndStickers: "Manage Emojis and Stickers",
  ManageGuildExpressions: "Manage Guild Expressions",
  UseApplicationCommands: "Use Application Commands",
  RequestToSpeak: "Request to Speak",
  ManageEvents: "Manage Events",
  ManageThreads: "Manage Threads",
  CreatePublicThreads: "Create Public Threads",
  CreatePrivateThreads: "Create Private Threads",
  UseExternalStickers: "Use External Stickers",
  SendMessagesInThreads: "Send Messages in Threads",
  UseEmbeddedActivities: "Use Embedded Activities",
  ModerateMembers: "Moderate Members",
  ViewCreatorMonetizationAnalytics: "View Creator Monetization Analytics",
  UseSoundboard: "Use Soundboard",
  CreateGuildExpressions: "Create Guild Expressions",
  CreateEvents: "Create Events",
  UseExternalSounds: "Use External Sounds",
  SendVoiceMessages: "Send Voice Messages",
  SendPolls: "Send Polls",
  UseExternalApps: "Use External Apps",
};
