/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ServersSplatImport } from './routes/servers/$'
import { Route as AuthSignUpSplatImport } from './routes/_auth/sign-up/$'
import { Route as AuthSignInSplatImport } from './routes/_auth/sign-in/$'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ServersSplatRoute = ServersSplatImport.update({
  id: '/servers/$',
  path: '/servers/$',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpSplatRoute = AuthSignUpSplatImport.update({
  id: '/_auth/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInSplatRoute = AuthSignInSplatImport.update({
  id: '/_auth/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/servers/$': {
      id: '/servers/$'
      path: '/servers/$'
      fullPath: '/servers/$'
      preLoaderRoute: typeof ServersSplatImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servers/$': typeof ServersSplatRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servers/$': typeof ServersSplatRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/servers/$': typeof ServersSplatRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servers/$' | '/sign-in/$' | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servers/$' | '/sign-in/$' | '/sign-up/$'
  id: '__root__' | '/' | '/servers/$' | '/_auth/sign-in/$' | '/_auth/sign-up/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServersSplatRoute: typeof ServersSplatRoute
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServersSplatRoute: ServersSplatRoute,
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/servers/$",
        "/_auth/sign-in/$",
        "/_auth/sign-up/$"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/servers/$": {
      "filePath": "servers/$.tsx"
    },
    "/_auth/sign-in/$": {
      "filePath": "_auth/sign-in/$.tsx"
    },
    "/_auth/sign-up/$": {
      "filePath": "_auth/sign-up/$.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
